import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'project-plan',
    {
      type: 'category',
      label: 'Goals and Requirements',
      items: [{type: 'autogenerated', dirName: 'goals-requirements'}],
    },
    {
      type: 'category',
      label: 'External Hosting Services',
      items: [{type: 'autogenerated', dirName: 'external-hosting-services'}],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      items: [{type: 'autogenerated', dirName: 'architecture-decisions'}],
    },
    {
      type: 'category',
      label: 'Data Models and Schemas',
      items: [{type: 'autogenerated', dirName: 'data-models-schemas'}],
    },
    {
      type: 'category',
      label: 'Implementation Details',
      items: [{type: 'autogenerated', dirName: 'deployment-strategy'}],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: [{type: 'autogenerated', dirName: 'miscellaneous'}],
    },
  ],
};

export default sidebars;
